//! Protocol Buffer encoding for CDC events.
//!
//! Uses [prost](https://crates.io/crates/prost) for efficient protobuf
//! serialization.  No `protoc` installation or `build.rs` code generation is
//! required — the Rust structs are defined directly with `prost` derive macros.
//!
//! The canonical `.proto` schema is documented in `proto/event.proto` in this
//! repository and can be used to generate bindings for any protobuf-compatible
//! language (Go, Python, Java, TypeScript, …).
//!
//! # Wire format
//!
//! The `before` and `after` row-image fields carry **UTF-8 JSON** encoded as
//! protobuf `bytes`.  This preserves the schemaless nature of the row payload
//! while remaining self-describing.  Consumers decode the bytes as a JSON
//! object and can optionally re-validate against a schema registry.
//!
//! # Schema version
//!
//! The generated bytes match schema version `1` (the current
//! `EVENT_ENVELOPE_VERSION`).  Field numbers are stable; new optional fields
//! will be added with new tag numbers in future minor versions.

use prost::Message;

use crate::codec::{EncodedOutput, EventEncoder};
use crate::core::{BeforeImage, Error, Event, Operation, Result};

const CONTENT_TYPE: &str = "application/x-protobuf";

// ─── ProtobufEncoder ──────────────────────────────────────────────────────────

/// Encodes CDC events as Protocol Buffer binary bytes.
///
/// The encoding corresponds to the schema in `proto/event.proto`.  Use that
/// file with `protoc` to generate deserialization bindings in any
/// protobuf-compatible language.
///
/// # Example
///
/// ```rust
/// # use rustcdc::codec::{EventEncoder, ProtobufEncoder};
/// # use rustcdc::{Event, Operation, SourceMetadata, EVENT_ENVELOPE_VERSION};
/// let encoder = ProtobufEncoder;
/// let event = Event::builder("users", Operation::Insert)
///     .after(serde_json::json!({"id": 1}))
///     .source(SourceMetadata::new("postgres", "0/16B6A70", 1))
///     .ts(1)
///     .build();
/// let out = encoder.encode(&event).unwrap();
/// assert_eq!(out.content_type, "application/x-protobuf");
/// ```
#[derive(Debug, Clone, Default)]
pub struct ProtobufEncoder;

impl EventEncoder for ProtobufEncoder {
    fn encode(&self, event: &Event) -> Result<EncodedOutput> {
        let proto = ProtoEvent::from_event(event)?;
        Ok(EncodedOutput::new(proto.encode_to_vec(), CONTENT_TYPE))
    }

    fn content_type(&self) -> &'static str {
        CONTENT_TYPE
    }
}

// ─── Proto message types ──────────────────────────────────────────────────────
//
// These structs mirror `proto/event.proto` exactly (same field names, numbers,
// and types).  If you update these structs you MUST update the proto file.

/// Protobuf representation of [`crate::core::Operation`].
///
/// Mirrors `enum Operation` in `proto/event.proto`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, prost::Enumeration)]
#[repr(i32)]
pub enum ProtoOperation {
    /// Default/unspecified — never emitted by a well-formed encoder.
    Unspecified = 0,
    /// Row created.
    Insert = 1,
    /// Row modified.
    Update = 2,
    /// Row removed.
    Delete = 3,
    /// Snapshot row, not a live change.
    Read = 4,
    /// Schema change (DDL).
    SchemaChange = 5,
    /// Table truncated.
    Truncate = 6,
    /// Logical decoding message written by the application.
    Message = 7,
}

impl ProtoOperation {
    fn from_op(op: Operation) -> Self {
        match op {
            Operation::Insert => Self::Insert,
            Operation::Update => Self::Update,
            Operation::Delete => Self::Delete,
            Operation::Read => Self::Read,
            Operation::SchemaChange => Self::SchemaChange,
            Operation::Truncate => Self::Truncate,
            Operation::Message => Self::Message,
        }
    }

    /// Convert back to the canonical [`Operation`].
    ///
    /// `Unspecified` is an error rather than a silent default: protobuf's zero value is
    /// indistinguishable from an absent field, so mapping it to `Insert` would turn a
    /// truncated or foreign message into a fabricated row creation.
    fn to_op(self) -> Result<Operation> {
        match self {
            Self::Insert => Ok(Operation::Insert),
            Self::Update => Ok(Operation::Update),
            Self::Delete => Ok(Operation::Delete),
            Self::Read => Ok(Operation::Read),
            Self::SchemaChange => Ok(Operation::SchemaChange),
            Self::Truncate => Ok(Operation::Truncate),
            Self::Message => Ok(Operation::Message),
            Self::Unspecified => Err(Error::SerializationError(
                "protobuf event carries OPERATION_UNSPECIFIED (the protobuf zero value), \
                 which means the `op` field was absent or the message was not produced by \
                 a rustcdc encoder. Refusing to guess an operation."
                    .into(),
            )),
        }
    }
}

/// Protobuf representation of [`crate::core::SourceMetadata`].
///
/// Mirrors `message SourceMetadata` in `proto/event.proto`.
#[derive(Clone, PartialEq, prost::Message)]
pub struct ProtoSourceMetadata {
    /// Logical connector name (e.g. `"postgres"`, `"mysql"`).
    #[prost(string, tag = "1")]
    pub source_name: String,
    /// Source-specific durable position (LSN, GTID, …).
    #[prost(string, tag = "2")]
    pub offset: String,
    /// Source timestamp in milliseconds since Unix epoch.
    #[prost(uint64, tag = "3")]
    pub timestamp: u64,
}

/// Protobuf representation of [`crate::core::SnapshotMetadata`].
///
/// Mirrors `message SnapshotMetadata` in `proto/event.proto`.
#[derive(Clone, PartialEq, prost::Message)]
pub struct ProtoSnapshotMetadata {
    /// Snapshot session identifier.
    #[prost(string, tag = "1")]
    pub snapshot_id: String,
    /// Zero-based chunk index.
    #[prost(uint32, tag = "2")]
    pub chunk_index: u32,
    /// Whether this is the final chunk.
    #[prost(bool, tag = "3")]
    pub is_last_chunk: bool,
}

/// Protobuf representation of [`crate::core::TransactionMetadata`].
///
/// Mirrors `message TransactionMetadata` in `proto/event.proto`.
#[derive(Clone, PartialEq, prost::Message)]
pub struct ProtoTransactionMetadata {
    /// Source transaction identifier.
    #[prost(uint64, tag = "1")]
    pub tx_id: u64,
    /// Total events in this transaction.
    ///
    /// **Sentinel:** `0` means "unknown" — the source connector did not know
    /// the transaction size at begin time (e.g. PostgreSQL WAL, MySQL binlog).
    /// Do **not** interpret `0` as an empty transaction.
    #[prost(uint32, tag = "2")]
    pub total_events: u32,
    /// Zero-based position of this event within the transaction.
    #[prost(uint32, tag = "3")]
    pub event_index: u32,
}

/// Protobuf representation of [`crate::core::Event`].
///
/// Mirrors `message Event` in `proto/event.proto`.
///
/// `before` and `after` are UTF-8 JSON bytes (`None` → absent field).
#[derive(Clone, PartialEq, prost::Message)]
pub struct ProtoEvent {
    /// JSON-encoded before-image (absent when `None`).
    #[prost(bytes = "vec", optional, tag = "1")]
    pub before: Option<Vec<u8>>,
    /// JSON-encoded after-image (absent when `None`).
    #[prost(bytes = "vec", optional, tag = "2")]
    pub after: Option<Vec<u8>>,
    /// CRUD operation.
    #[prost(enumeration = "ProtoOperation", tag = "3")]
    pub op: i32,
    /// Source identity and durable offset.
    #[prost(message, optional, tag = "4")]
    pub source: Option<ProtoSourceMetadata>,
    /// Event timestamp in milliseconds since Unix epoch.
    #[prost(uint64, tag = "5")]
    pub ts: u64,
    /// Schema name (absent when unknown).
    #[prost(string, optional, tag = "6")]
    pub schema: Option<String>,
    /// Table name.
    #[prost(string, tag = "7")]
    pub table: String,
    /// Primary key column names (empty when unknown).
    #[prost(string, repeated, tag = "8")]
    pub primary_key: Vec<String>,
    /// Snapshot metadata (absent outside snapshot phase).
    #[prost(message, optional, tag = "9")]
    pub snapshot: Option<ProtoSnapshotMetadata>,
    /// Transaction metadata (absent for single-event transactions).
    #[prost(message, optional, tag = "10")]
    pub transaction: Option<ProtoTransactionMetadata>,
    /// Canonical envelope schema version.
    #[prost(uint32, tag = "11")]
    pub envelope_version: u32,
    /// True when `before` contains only primary-key columns (PostgreSQL DEFAULT REPLICA IDENTITY).
    #[prost(bool, tag = "12")]
    pub before_is_key_only: bool,
    /// Columns absent from `after` because the source could not supply them
    /// (PostgreSQL unchanged-TOAST). Absent, not null — see `Event::unavailable_columns`.
    #[prost(string, repeated, tag = "13")]
    pub unavailable_columns: Vec<String>,
    /// The same, for `before`. Never merged with `unavailable_columns` — the two sets
    /// differ, and merging them marks genuinely-changed columns as unwritable.
    #[prost(string, repeated, tag = "14")]
    pub before_unavailable_columns: Vec<String>,
    /// The table shape this row was captured under, as named by its schema announcement
    /// (absent when the connector could not derive it) — see `Event::schema_id`.
    #[prost(string, optional, tag = "15")]
    pub schema_id: Option<String>,
}

/// Protobuf representation of a CDC event's primary key.
///
/// Mirrors `message EventKey` in `proto/event_key.proto`, and carries the same payload
/// as [`KEY_AVRO_SCHEMA`] and [`KEY_JSON_SCHEMA`]: the primary key as a JSON object
/// encoded in a string, absent for keyless events.
///
/// [`KEY_AVRO_SCHEMA`]: crate::codec::KEY_AVRO_SCHEMA
/// [`KEY_JSON_SCHEMA`]: crate::codec::KEY_JSON_SCHEMA
#[derive(Clone, PartialEq, prost::Message)]
pub struct ProtoEventKey {
    /// JSON object mapping primary-key column names to values; `None` for keyless events.
    #[prost(string, optional, tag = "1")]
    pub key: Option<String>,
}

impl ProtoEventKey {
    /// Build the key message for an event.
    ///
    /// `key` is `None` — an absent protobuf field, not an empty string — when the event
    /// declares no primary key, when none of the key columns appear in the row image, or
    /// for the keyless operations (TRUNCATE, SCHEMA_CHANGE).
    pub fn from_event(event: &Event) -> Result<Self> {
        let key = event
            .primary_key_values()
            .map(|value| serde_json::to_string(&value))
            .transpose()
            .map_err(|e| Error::SerializationError(format!("protobuf key encode: {e}")))?;
        Ok(Self { key })
    }
}

impl ProtoEvent {
    /// Convert a [`crate::core::Event`] into its protobuf representation.
    pub fn from_event(event: &Event) -> Result<Self> {
        let before = event
            .before
            .row()
            .map(serde_json::to_vec)
            .transpose()
            .map_err(|e| Error::SerializationError(format!("protobuf before encode: {e}")))?;

        let after = event
            .after
            .as_ref()
            .map(serde_json::to_vec)
            .transpose()
            .map_err(|e| Error::SerializationError(format!("protobuf after encode: {e}")))?;

        Ok(Self {
            before,
            after,
            op: ProtoOperation::from_op(event.op) as i32,
            source: Some(ProtoSourceMetadata {
                source_name: event.source.source_name.clone(),
                offset: event.source.offset.clone(),
                timestamp: event.source.timestamp,
            }),
            ts: event.ts,
            schema: event.schema.clone(),
            table: event.table.clone(),
            primary_key: event.primary_key.clone().unwrap_or_default(),
            snapshot: event.snapshot.as_ref().map(|s| ProtoSnapshotMetadata {
                snapshot_id: s.snapshot_id.clone(),
                chunk_index: s.chunk_index,
                is_last_chunk: s.is_last_chunk,
            }),
            transaction: event
                .transaction
                .as_ref()
                .map(|t| ProtoTransactionMetadata {
                    tx_id: t.tx_id,
                    // `total_events` is `None` when the source does not know the
                    // transaction size at begin time (e.g. PostgreSQL logical
                    // replication, MySQL binlog streaming).  We encode `None` as
                    // the protobuf default value `0`.  Downstream consumers MUST
                    // treat `total_events == 0` as "unknown" rather than "empty
                    // transaction".  The proto field comment in `event.proto`
                    // documents the same sentinel.
                    total_events: t.total_events.unwrap_or(0),
                    event_index: t.event_index,
                }),
            envelope_version: event.envelope_version as u32,
            schema_id: event.schema_id.clone(),
            before_is_key_only: event.before.is_key_only(),
            unavailable_columns: event.unavailable_columns.clone(),
            before_unavailable_columns: event.before.unavailable_columns().to_vec(),
        })
    }

    /// Decode a `ProtoEvent` from raw protobuf bytes.
    pub fn from_bytes(bytes: &[u8]) -> Result<Self> {
        Self::decode(bytes).map_err(|e| Error::SerializationError(format!("protobuf decode: {e}")))
    }

    /// Convert back into the canonical [`crate::core::Event`].
    ///
    /// The inverse of [`ProtoEvent::from_event`]. Round-tripping is exact except for
    /// `TransactionMetadata::total_events`, where protobuf cannot distinguish "absent"
    /// from zero — `0` decodes back to `None`, matching the sentinel documented in
    /// `proto/event.proto`.
    ///
    /// # Errors
    ///
    /// Returns [`Error::SerializationError`] if `op` is unset, `source` is missing, or a
    /// row image is not valid JSON. All are permanent: the same bytes will never decode.
    pub fn into_event(self) -> Result<Event> {
        use crate::core::{SnapshotMetadata, SourceMetadata, TransactionMetadata};

        let decode_payload =
            |bytes: Option<Vec<u8>>, which: &str| -> Result<Option<serde_json::Value>> {
                bytes
                    .map(|raw| {
                        serde_json::from_slice(&raw).map_err(|error| {
                            Error::SerializationError(format!(
                                "protobuf {which}-image is not valid JSON: {error}"
                            ))
                        })
                    })
                    .transpose()
            };

        let op = ProtoOperation::try_from(self.op)
            .map_err(|_| {
                Error::SerializationError(format!(
                    "protobuf event carries unknown operation discriminant {}",
                    self.op
                ))
            })?
            .to_op()?;

        let source = self.source.ok_or_else(|| {
            Error::SerializationError(
                "protobuf event has no `source` metadata, so it carries no durable position \
                 and cannot be checkpointed"
                    .into(),
            )
        })?;

        // The flat protobuf triple is reassembled through the one shared constructor, so a
        // self-contradictory message is refused here exactly as it would be over JSON.
        let before = BeforeImage::from_wire_parts(
            decode_payload(self.before, "before")?,
            self.before_is_key_only,
            self.before_unavailable_columns,
        )
        .map_err(Error::SerializationError)?;

        Ok(Event {
            before,
            after: decode_payload(self.after, "after")?,
            op,
            source: SourceMetadata {
                source_name: source.source_name,
                offset: source.offset,
                timestamp: source.timestamp,
            },
            ts: self.ts,
            schema: self.schema,
            table: self.table,
            primary_key: (!self.primary_key.is_empty()).then_some(self.primary_key),
            snapshot: self.snapshot.map(|s| SnapshotMetadata {
                snapshot_id: s.snapshot_id,
                chunk_index: s.chunk_index,
                is_last_chunk: s.is_last_chunk,
            }),
            transaction: self.transaction.map(|t| TransactionMetadata {
                tx_id: t.tx_id,
                // `0` is protobuf's zero value and the documented "unknown" sentinel —
                // it is not an empty transaction.
                total_events: (t.total_events != 0).then_some(t.total_events),
                event_index: t.event_index,
            }),
            envelope_version: self.envelope_version as u16,
            schema_id: self.schema_id,
            unavailable_columns: self.unavailable_columns,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::{
        EVENT_ENVELOPE_VERSION, Event, Operation, SnapshotMetadata, SourceMetadata,
        TransactionMetadata,
    };

    fn full_event() -> Event {
        Event {
            before: BeforeImage::full(serde_json::json!({"id": 1, "name": "alice"})),
            after: Some(serde_json::json!({"id": 1, "name": "alice-v2"})),
            op: Operation::Update,
            source: SourceMetadata {
                source_name: "postgres".into(),
                offset: "0/16B6A70".into(),
                timestamp: 1716595200000,
            },
            ts: 1716595200000,
            schema: Some("public".into()),
            table: "users".into(),
            primary_key: Some(vec!["id".into()]),
            snapshot: Some(SnapshotMetadata {
                snapshot_id: "snap-1".into(),
                chunk_index: 0,
                is_last_chunk: false,
            }),
            transaction: Some(TransactionMetadata {
                tx_id: 42,
                total_events: Some(3),
                event_index: 1,
            }),
            envelope_version: EVENT_ENVELOPE_VERSION,
            schema_id: None,
            unavailable_columns: Vec::new(),
        }
    }

    fn insert_event() -> Event {
        Event {
            before: BeforeImage::Unavailable,
            after: Some(serde_json::json!({"id": 1})),
            op: Operation::Insert,
            source: SourceMetadata {
                source_name: "mysql".into(),
                offset: "gtid:abc".into(),
                timestamp: 1,
            },
            ts: 1,
            schema: None,
            table: "orders".into(),
            primary_key: None,
            snapshot: None,
            transaction: None,
            envelope_version: EVENT_ENVELOPE_VERSION,
            schema_id: None,
            unavailable_columns: Vec::new(),
        }
    }

    #[test]
    fn encode_produces_non_empty_bytes() {
        let enc = ProtobufEncoder;
        let out = enc.encode(&insert_event()).unwrap();
        assert!(!out.bytes.is_empty());
        assert_eq!(out.content_type, "application/x-protobuf");
    }

    #[test]
    fn proto_roundtrip_preserves_all_fields() {
        let event = full_event();
        let proto = ProtoEvent::from_event(&event).unwrap();
        let bytes = proto.encode_to_vec();
        let decoded = ProtoEvent::from_bytes(&bytes).unwrap();

        assert_eq!(decoded.table, "users");
        assert_eq!(decoded.op, ProtoOperation::Update as i32);
        assert_eq!(decoded.schema, Some("public".into()));
        assert_eq!(decoded.primary_key, vec!["id"]);
        assert_eq!(decoded.ts, 1716595200000);
        assert_eq!(decoded.envelope_version, EVENT_ENVELOPE_VERSION as u32);

        // before/after are JSON bytes
        let before: serde_json::Value =
            serde_json::from_slice(decoded.before.as_ref().unwrap()).unwrap();
        assert_eq!(before["name"], "alice");
        let after: serde_json::Value =
            serde_json::from_slice(decoded.after.as_ref().unwrap()).unwrap();
        assert_eq!(after["name"], "alice-v2");

        // source
        let src = decoded.source.unwrap();
        assert_eq!(src.source_name, "postgres");
        assert_eq!(src.offset, "0/16B6A70");

        // snapshot
        let snap = decoded.snapshot.unwrap();
        assert_eq!(snap.snapshot_id, "snap-1");
        assert!(!snap.is_last_chunk);

        // transaction
        let tx = decoded.transaction.unwrap();
        assert_eq!(tx.tx_id, 42);
        assert_eq!(tx.total_events, 3);
        assert_eq!(tx.event_index, 1);

        assert!(!decoded.before_is_key_only);
    }

    #[test]
    fn insert_event_has_no_before_field() {
        let event = insert_event();
        let proto = ProtoEvent::from_event(&event).unwrap();
        assert!(proto.before.is_none());
        assert!(proto.after.is_some());
        assert_eq!(proto.op, ProtoOperation::Insert as i32);
    }

    #[test]
    fn all_operations_encode_correctly() {
        let ops = [
            (Operation::Insert, ProtoOperation::Insert),
            (Operation::Update, ProtoOperation::Update),
            (Operation::Delete, ProtoOperation::Delete),
            (Operation::Read, ProtoOperation::Read),
            (Operation::SchemaChange, ProtoOperation::SchemaChange),
            (Operation::Truncate, ProtoOperation::Truncate),
        ];
        for (op, expected) in ops {
            let mut ev = insert_event();
            ev.op = op;
            let proto = ProtoEvent::from_event(&ev).unwrap();
            assert_eq!(proto.op, expected as i32, "op mismatch for {op:?}");
        }
    }

    #[test]
    fn before_is_key_only_round_trips_through_proto() {
        let mut event = full_event();
        event.before = BeforeImage::key_only(
            event
                .before
                .row()
                .cloned()
                .expect("fixture has a before-image"),
        );
        let proto = ProtoEvent::from_event(&event).unwrap();
        let bytes = proto.encode_to_vec();
        let decoded = ProtoEvent::from_bytes(&bytes).unwrap();
        assert!(decoded.before_is_key_only);
    }

    #[test]
    fn content_type_is_x_protobuf() {
        assert_eq!(ProtobufEncoder.content_type(), "application/x-protobuf");
    }

    // ─── ProtoEventKey ───────────────────────────────────────────────────────

    #[test]
    fn proto_event_key_carries_the_primary_key_as_json() {
        let event = full_event();
        let key = ProtoEventKey::from_event(&event).unwrap();
        let json: serde_json::Value =
            serde_json::from_str(key.key.as_deref().expect("keyed event")).unwrap();
        assert_eq!(json, event.primary_key_values().unwrap());
    }

    #[test]
    fn proto_event_key_is_absent_not_empty_for_keyless_events() {
        // Absent, not "": a consumer has to be able to tell "no key" from "a key that
        // serialised to nothing", and protobuf's empty string is indistinguishable from
        // an unset non-optional field.
        let mut event = full_event();
        event.primary_key = None;
        let key = ProtoEventKey::from_event(&event).unwrap();
        assert!(key.key.is_none());

        let bytes = key.encode_to_vec();
        assert!(
            bytes.is_empty(),
            "an absent optional field must occupy no bytes on the wire"
        );
    }

    #[test]
    fn proto_event_key_round_trips() {
        let event = full_event();
        let bytes = ProtoEventKey::from_event(&event).unwrap().encode_to_vec();
        let decoded = <ProtoEventKey as prost::Message>::decode(&bytes[..]).unwrap();
        assert_eq!(decoded.key.as_deref(), Some(r#"{"id":1}"#));
    }
}
